import fs from "fs-extra";
import path from "node:path";
import { CODEX_MCP_BLOCK_END, CODEX_MCP_BLOCK_START, logWarn, readJsonFile } from "../core.js";
import { discoverBundledSkills, projectSkillsForAgent } from "./common.js";

function tomlString(value) {
  return JSON.stringify(String(value ?? ""));
}

function tomlArray(values) {
  const items = (Array.isArray(values) ? values : []).map((value) => tomlString(value));
  return `[${items.join(", ")}]`;
}

function tomlInlineTable(values) {
  const entries = values && typeof values === "object" && !Array.isArray(values) ? values : {};
  const keys = Object.keys(entries).sort((left, right) => left.localeCompare(right));
  const pairs = keys.map((key) => `${tomlTableKey(key)} = ${tomlString(entries[key])}`);
  return `{ ${pairs.join(", ")} }`;
}

function tomlTableKey(key) {
  return JSON.stringify(String(key));
}

function isTomlTableHeader(value) {
  return /^\[\[?.+\]\]?$/.test(value);
}

function isCodexMcpTableHeader(value) {
  return /^\[mcp_servers\./.test(value);
}

export function renderCodexConfigToml(canonicalMcp, bundledSkills = []) {
  const servers = canonicalMcp?.mcpServers ?? {};
  const names = Object.keys(servers).sort((left, right) => left.localeCompare(right));
  const lines = [
    "# Generated by skills-sync. Managed file.",
    "# Source: ~/.skills-sync/internal/common/mcp.json",
    'model = "gpt-5-codex"',
    'approval_policy = "on-request"',
    'sandbox_mode = "workspace-write"',
    ""
  ];

  const sortedSkills = [...bundledSkills].sort((left, right) => left.localeCompare(right));
  for (const skill of sortedSkills) {
    lines.push("[[skills.config]]");
    lines.push(`path = ${tomlString(`~/.codex/skills/vendor_imports/${skill}`)}`);
    lines.push("enabled = true");
    lines.push("");
  }

  for (const name of names) {
    const server = servers[name] ?? {};
    lines.push(`[mcp_servers.${tomlTableKey(name)}]`);
    if (typeof server.url === "string" && server.url.trim().length > 0) {
      lines.push(`url = ${tomlString(server.url)}`);
    } else {
      lines.push('transport = "stdio"');
      lines.push(`command = ${tomlString(server.command)}`);
      lines.push(`args = ${tomlArray(server.args)}`);
      if (server.env && typeof server.env === "object" && !Array.isArray(server.env) && Object.keys(server.env).length > 0) {
        lines.push(`env = ${tomlInlineTable(server.env)}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderCodexMcpTables(canonicalMcp) {
  const servers = canonicalMcp?.mcpServers ?? {};
  const names = Object.keys(servers).sort((left, right) => left.localeCompare(right));
  const lines = [];

  for (const name of names) {
    const server = servers[name] ?? {};
    lines.push(`[mcp_servers.${tomlTableKey(name)}]`);
    if (typeof server.url === "string" && server.url.trim().length > 0) {
      lines.push(`url = ${tomlString(server.url)}`);
    } else {
      lines.push('transport = "stdio"');
      lines.push(`command = ${tomlString(server.command)}`);
      lines.push(`args = ${tomlArray(server.args)}`);
      if (server.env && typeof server.env === "object" && !Array.isArray(server.env) && Object.keys(server.env).length > 0) {
        lines.push(`env = ${tomlInlineTable(server.env)}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function extractCodexMcpTables(content) {
  const normalized = String(content ?? "").replace(/\r\n/g, "\n");
  const lines = normalized.split("\n");
  const blocks = [];

  let index = 0;
  while (index < lines.length) {
    const trimmed = lines[index].trim();
    if (!isCodexMcpTableHeader(trimmed)) {
      index += 1;
      continue;
    }

    const block = [lines[index]];
    index += 1;
    while (index < lines.length) {
      const candidate = lines[index].trim();
      if (isTomlTableHeader(candidate)) {
        break;
      }
      block.push(lines[index]);
      index += 1;
    }
    blocks.push(block.join("\n").trimEnd());
  }

  if (blocks.length === 0) {
    return "";
  }
  return `${blocks.join("\n\n").trimEnd()}\n`;
}

export function renderCodexConfigTomlFromLocal(localContent, canonicalMcp) {
  const normalized = String(localContent ?? "").replace(/\r\n/g, "\n");
  const lines = normalized.split("\n");
  const preserved = [];

  let index = 0;
  while (index < lines.length) {
    const trimmed = lines[index].trim();

    if (trimmed === CODEX_MCP_BLOCK_START) {
      index += 1;
      while (index < lines.length && lines[index].trim() !== CODEX_MCP_BLOCK_END) {
        index += 1;
      }
      if (index < lines.length) {
        index += 1;
      }
      continue;
    }

    if (isCodexMcpTableHeader(trimmed)) {
      index += 1;
      while (index < lines.length) {
        const candidate = lines[index].trim();
        if (isTomlTableHeader(candidate)) {
          break;
        }
        index += 1;
      }
      continue;
    }

    preserved.push(lines[index]);
    index += 1;
  }

  const base = preserved.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd();
  const mcpTables = renderCodexMcpTables(canonicalMcp).trimEnd();
  return `${base.length > 0 ? `${base}\n\n` : ""}${mcpTables}\n`;
}

export async function projectCodexFromBundle(options) {
  const {
    runtimeInternalRoot,
    bundleSkillsPath,
    bundleMcpPath,
    packRoot,
    localConfigPath = null,
    hasNonMcpConfig = false
  } = options;
  const runtimeRoot = path.join(runtimeInternalRoot, ".codex");
  await fs.ensureDir(runtimeRoot);

  const { skillsMethod, projectionPlan } = await projectSkillsForAgent(
    bundleSkillsPath,
    path.join(runtimeRoot, "skills"),
    "codex"
  );
  await projectSkillsForAgent(bundleSkillsPath, path.join(runtimeRoot, "vendor_imports", "skills"), "codex");

  const canonicalMcp = await readJsonFile(bundleMcpPath);
  let codexToml = null;

  if (hasNonMcpConfig && localConfigPath && (await fs.pathExists(localConfigPath))) {
    try {
      const localContent = await fs.readFile(localConfigPath, "utf8");
      codexToml = renderCodexConfigTomlFromLocal(localContent, canonicalMcp);
    } catch (error) {
      logWarn(`Failed to seed Codex runtime config from local settings: ${error.message}`);
    }
  }

  if (!codexToml) {
    const bundledSkills = await discoverBundledSkills(bundleSkillsPath);
    codexToml = renderCodexConfigToml(canonicalMcp, bundledSkills);
  }

  const runtimeConfigPath = path.join(runtimeRoot, "config.toml");
  await fs.writeFile(runtimeConfigPath, codexToml, "utf8");
  const mcpMethod = "generated";

  const overrideSource = path.join(packRoot, "tool-overrides", "codex");
  if (await fs.pathExists(overrideSource)) {
    await fs.copy(overrideSource, path.join(runtimeRoot, "tool-overrides"));
  }

  return {
    skillsMethod,
    mcpMethod,
    projectionPlan
  };
}

export const projectFromBundle = projectCodexFromBundle;
